import {useState} from 'react';
import {NavLink,Link,Outlet,useNavigate,useLocation,Navigate} from 'react-router-dom';
import {LayoutDashboard,UserRound,Network,ChartNoAxesCombined,Route,BookOpen,ClipboardCheck,TrendingUp,Sparkles,Users,Upload,Building2,ChartColumn,Target,FileText,Settings,Bell,Search,ChevronDown,Menu,HelpCircle,LogOut,ArrowUpRight,ShieldCheck,X} from 'lucide-react';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,DropdownMenuLabel,DropdownMenuSeparator} from './ui/dropdown-menu';
import {useDemo} from '../context/DemoContext';
import {Brand,Badge,Footer,Modal,Loading,Btn,Breadcrumb,ThemeToggle} from './Common';
import {api} from '../lib/api';
const employee=[['My Profile','profile',UserRound],['Dashboard','dashboard',LayoutDashboard],['Virtual Assistant','assistant',Sparkles],['Competency Map','competencies',Network],['Skill Gap Analysis','gaps',ChartNoAxesCombined],['Learning Path','learning',Route],['iGOT Courses','courses',BookOpen],['Assessments','assessments',ClipboardCheck],['Progress','progress',TrendingUp]];
const trainer=[['Trainer Dashboard','trainer',LayoutDashboard],['Learners','learners',Users],['Assessments','assessments',ClipboardCheck],['Upload Material','upload',Upload],['Competency Analytics','trainer-analytics',ChartColumn]];
const admin=[['Admin Dashboard','admin',LayoutDashboard],['Workforce Analytics','workforce',ChartColumn],['Department Insights','departments',Building2],['Competency Gaps','org-gaps',Target],['Training Effectiveness','effectiveness',TrendingUp],['Future Skills','future',Sparkles],['Reports','reports',FileText],['User Management','users',Users]];
export const roleHome=r=>r==='employee'?'/app/dashboard':r==='trainer'?'/app/trainer':'/app/admin';
export const Layout=()=>{
 const {data,loading,error,refresh,role,login,logout,act}=useDemo(),navigate=useNavigate(),location=useLocation();
 const [mobile,setMobile]=useState(false),[help,setHelp]=useState(false),[query,setQuery]=useState(''),[switching,setSwitching]=useState(false),[collapsed,setCollapsed]=useState(false);
 if(!role)return <Navigate to="/login" replace/>;
 const nav=role==='employee'?employee:role==='trainer'?trainer:admin;
 const name=data?.profile.name||(role==='trainer'?'NSSTA Officer':role==='employee'?'Ananya Sharma':'Priya Menon');
 const designation=data?.profile.designation||(role==='trainer'?'NSSTA Officer':role==='super-admin'?'Super Administrator':'Workforce Administrator');
 const switchRole=async r=>{setSwitching(true);try{await login(r);navigate(roleHome(r));setMobile(false);}finally{setSwitching(false);}};
 return <div className={`app-shell ${collapsed?'sidebar-collapsed':''}`}><div className="prototype-strip" data-testid="prototype-banner"><span><span className="india-mark"><i/><i/><i/></span> A capacity-building initiative for India's statistical workforce</span><span><span className="status-dot"/> Secure learning environment</span></div>
 <header className="global-header"><div className="header-brand"><button className="icon-button mobile-menu" aria-label="Open navigation" data-testid="mobile-menu-button" onClick={()=>setMobile(!mobile)}>{mobile?<X size={22}/>:<Menu size={22}/>}</button><button className="icon-button sidebar-collapse-button" aria-label={collapsed?'Expand sidebar':'Collapse sidebar'} data-testid="sidebar-collapse-button" onClick={()=>setCollapsed(!collapsed)}>{collapsed?<ChevronDown size={18}/>:<Menu size={18}/>}</button><Link to={roleHome(role)} data-testid="header-home-link"><Brand compact/></Link></div><form className="global-search" onSubmit={e=>{e.preventDefault();if(query.trim()){navigate(`/app/courses?q=${encodeURIComponent(query)}`);setQuery('');}}}><Search size={17}/><input placeholder="Search competencies, courses and more..." value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search platform" data-testid="global-search-input"/><kbd>↵</kbd></form><div className="header-tools"><button className="icon-button" title="Help & support" aria-label="Help and support" data-testid="header-help-button" onClick={()=>setHelp(true)}><HelpCircle size={20}/></button><DropdownMenu><DropdownMenuTrigger asChild><button className="icon-button notification-bell" aria-label="Notifications" data-testid="notifications-button"><Bell size={20}/>{!data?.notifications_read&&<i/>}</button></DropdownMenuTrigger><DropdownMenuContent align="end" className="notification-menu"><DropdownMenuLabel>Notifications</DropdownMenuLabel>{data?.notifications.map(n=><DropdownMenuItem key={n.id} data-testid={`notification-${n.id}`} onSelect={()=>{navigate(n.route);act(()=>api.post('/notifications/read')).catch(()=>{});}}><div><strong>{n.title}</strong><p>{n.text}</p></div></DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu><span className="header-separator"/><DropdownMenu><DropdownMenuTrigger asChild><button className="profile-trigger" data-testid="profile-menu-button" disabled={switching}><span className="avatar">{name.split(' ').slice(0,2).map(n=>n[0]).join('')}</span><span className="profile-trigger-text"><strong>{name}</strong><small>{designation}</small></span><ChevronDown size={14}/></button></DropdownMenuTrigger><DropdownMenuContent align="end" className="profile-menu"><DropdownMenuLabel>Demo role · {role}</DropdownMenuLabel><DropdownMenuSeparator/>{[['employee','Employee'],['admin','Administrator']].map(([r,label])=><DropdownMenuItem data-testid={`switch-role-${r}`} key={r} onSelect={()=>switchRole(r)}>{r===role?'✓ ':''}Login as {label}</DropdownMenuItem>)}<DropdownMenuSeparator/><DropdownMenuItem data-testid="logout-button" onSelect={()=>{logout();navigate('/login');}}><LogOut size={15}/> Sign out</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></header>
 {mobile&&<button className="sidebar-overlay" aria-label="Close navigation" data-testid="sidebar-overlay" onClick={()=>setMobile(false)}/>}
 <aside className={`sidebar ${mobile?'is-open':''} ${collapsed?'is-collapsed':''}`}><div className="workspace-label">{role==='employee'?'OFFICER WORKSPACE':role==='trainer'?'TRAINER WORKSPACE':'ADMINISTRATION'}</div><nav aria-label="Main navigation">{nav.map(([label,path,Icon],i)=><NavLink end to={`/app/${path}`} key={path} data-testid={`nav-${path}`} className={({isActive})=>`nav-item ${isActive?'active':''} ${path==='assistant'?'nav-ai':''}`} onClick={()=>setMobile(false)}><Icon size={18}/><span>{label}</span>{path==='assessments'&&<span className="nav-count">1</span>}{path==='assistant'&&<span className="ai-tag">VA</span>}</NavLink>)}</nav><div className="sidebar-bottom"><div className="sidebar-initiative"><div className="initiative-icon"><ShieldCheck size={21}/></div><strong>Building a stronger<br/>statistical workforce</strong><p>Learn. Upskill. Empower.</p><span>SMART INDIA HACKATHON 2026</span></div><button className="support-link" data-testid="sidebar-support-button" onClick={()=>setHelp(true)}><HelpCircle size={17}/>Help & Support<ArrowUpRight size={14}/></button><div className="sidebar-version">SANKHYASHAKTI <span>v1.0</span></div></div></aside>
 <div className="main-container"><div className="content-wrap"><div className="workspace-topline"><Breadcrumb name={nav.find(n=>location.pathname===`/app/${n[1]}`)?.[0]||'Learning workspace'}/><span className="organization-indicator"><Building2 size={13}/>{role==='employee'?data?.profile.department:role==='trainer'?'NSSTA · Training & Development':'Official Statistical System'}<Badge tone="neutral" testId="role-indicator">{role==='employee'?'Statistical Officer':role==='trainer'?'Trainer':role==='super-admin'?'Super Admin':'Administrator'}</Badge></span></div>{loading?<Loading/>:error?<div className="empty-state" role="alert" data-testid="load-error"><h2>We couldn’t load your workspace</h2><p>{error}</p><Btn data-testid="retry-load-button" onClick={()=>refresh().catch(()=>{})}>Try again</Btn></div>:<Outlet/>}</div><Footer/></div>
 <Modal open={help} onClose={()=>setHelp(false)} title="Help & Support" description="Sankhyashakti support"><div className="help-content" data-testid="help-content"><h3>Your workspace</h3><p>Explore your competency profile, complete an assessment, and track the resulting skill-gap changes. Role switching is available in the profile menu.</p><h3>Privacy & security</h3><p>Use sample documents only. Profile edits and results are stored against this browser’s anonymous session. This platform is not an official government website, is not certified, and is not connected to live iGOT, NSSTA or SSO systems.</p><h3>Accessibility</h3><p>Keyboard-accessible navigation, clear focus indicators, text equivalents for charts and responsive layouts are included.</p><Btn data-testid="help-close-button" onClick={()=>setHelp(false)}>Back to workspace</Btn></div></Modal></div>;
};