import {BrowserRouter,Routes,Route,Navigate,useLocation} from 'react-router-dom';
import {useEffect} from 'react';
import {Toaster} from './components/ui/sonner';
import {DemoProvider,useDemo} from './context/DemoContext';
import {Layout,roleHome} from './components/Layout';
import {Btn,ThemeToggle} from './components/Common';
import Landing,{Login} from './pages/PublicPages';
import Register from './pages/Register';
import Dashboard from './pages/Dashboard';
import Competencies from './pages/Competencies';
import LearningPath from './pages/LearningPath';
import Courses,{CourseDetail} from './pages/Courses';
import LearningMaterial from './pages/LearningMaterial';
import Assessments,{AssessmentResults} from './pages/Assessments';
import Profile from './pages/ProfileSafe';
import Progress from './pages/Progress';
import Assistant from './pages/Assistant';
import UploadMaterial from './pages/UploadMaterial';
import Trainer,{Learners} from './pages/Trainer';
import Admin from './pages/Admin';
import Reports from './pages/Reports';
import Users from './pages/Users';
import './App.css';
import './Accessibility.css';
import './styles/exports.css';
import './styles/public-refinements.css';
const Guard=({roles,children})=>{const {role}=useDemo();return roles.includes(role)?children:<Navigate to={roleHome(role)} replace/>;};
const RootRedirect=()=>{const {role}=useDemo();return <Navigate to={role?roleHome(role):'/login'} replace/>;};
const ScrollToTop=()=>{const {pathname}=useLocation();useEffect(()=>{window.scrollTo(0,0);document.title='iGOT Sankhyashakti | Competency Intelligence';},[pathname]);return <ThemeToggle/>;};
const GlobalThemeToggle=()=> <ThemeToggle/>;
function App(){return <BrowserRouter><DemoProvider><ScrollToTop/><Routes><Route path="/" element={<Landing/>}/><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="/app" element={<Layout/>}><Route index element={<RootRedirect/>}/><Route path="dashboard" element={<Dashboard/>}/><Route path="profile" element={<Profile/>}/><Route path="competencies" element={<Competencies/>}/><Route path="gaps" element={<Competencies gaps/>}/><Route path="learning" element={<LearningPath/>}/><Route path="courses" element={<Courses/>}/><Route path="courses/:id" element={<CourseDetail/>}/><Route path="courses/:id/material" element={<LearningMaterial/>}/><Route path="assessments" element={<Assessments/>}/><Route path="results/:id" element={<AssessmentResults/>}/><Route path="progress" element={<Progress/>}/><Route path="assistant" element={<Assistant/>}/><Route path="upload" element={<UploadMaterial/>}/><Route path="trainer" element={<Guard roles={['trainer']}><Trainer/></Guard>}/><Route path="trainer-analytics" element={<Guard roles={['trainer']}><Trainer analytics/></Guard>}/><Route path="learners" element={<Guard roles={['trainer','admin','super-admin']}><Learners/></Guard>}/>{[['admin','dashboard'],['workforce','workforce'],['departments','departments'],['org-gaps','org-gaps'],['effectiveness','effectiveness'],['future','future']].map(([path,view])=><Route key={path} path={path} element={<Guard roles={['admin','super-admin']}><Admin key={view} view={view}/></Guard>}/>)}<Route path="reports" element={<Guard roles={['admin','super-admin']}><Reports/></Guard>}/><Route path="users" element={<Guard roles={['admin','super-admin']}><Users/></Guard>}/><Route path="*" element={<div className="empty-state" data-testid="not-found"><h1>Page not found</h1><p>Let’s get you back to your workspace.</p><Btn to="/app" data-testid="return-workspace">Back to Workspace</Btn></div>}/></Route><Route path="*" element={<Navigate to="/" replace/>}/></Routes><Toaster position="bottom-right" richColors closeButton/></DemoProvider></BrowserRouter>}
export default App;